#!/bin/sh

operationg_systems=(ios macos)
architectures=(arm64)
    
for arch in "${architectures[@]}"; do
	for os in "${operationg_systems[@]}"; do
		if [ -d "build/$arch-$os" ]; then
			echo "Building $arch-$os"
			cd "build/$arch-$os/lib"
			libtool -o libspatialiteall.a *.a
			cd -
		else
			echo "Skipping $arch-$os"
		fi
	done
done

# Make framework
xcodebuild -create-xcframework -library build/arm64-ios/lib/libspatialiteall.a -headers include/ -library build/arm64-macos/lib/libspatialiteall.a -headers include/ -output libspatialite.xcframework
